### PR TITLE
1020015 - enable Foreman's manage_puppetca for Puppet CA functionality

### PR DESCRIPTION
**Pull request by domcleal**
https://bugzilla.redhat.com/show_bug.cgi?id=1020015

### CODE REVIEW

**Comment by iNecas** [comment]
I wonder if it's better to rely on the default value or setting that explicitly to true?

**Comment by domcleal** [comment]
I don't think we'll ever set the default to false.  The only thing I've thought of since is if katello-configure's used for upgrades, then we might want it explicitly set.

**Comment by iNecas** [comment]
@domcleal yeah, I think having it setting to true explicitly is better, as that's what we want it to do :)

**Comment by domcleal** [comment]
@iNecas no problem, updated!

**Comment by iNecas** [comment]
ACK

**Pull request merged**
