### PR TITLE
scl_root - add parameter and use in puppet template

### PR DESCRIPTION
**Pull request by bbuckingham**
Since we'll support installing with puppet based on SCL, we
need to have the puppet.conf in the foreman config point
to the location within the SCL path.  This adds a parameter
that we can use elsewhere, if needed.

### CODE REVIEW

**Comment by domcleal** [comment]
This does need to be fixed, but I'm thinking it opens a few new questions, i.e. whether the config should be relocated at all.

I witnessed OpenCSW try and do this and it caused the maintainers quite a bit of pain, as Puppet has /etc/puppet hardcoded as a default path.  Other paths such as /var/lib/puppet would also need reconfiguring, which might surprise people, scripts and tools.

Thoughts?

**Comment by domcleal** [comment]
(I forgot to say otherwise, :+1:)

**Comment by mccun934** [comment]
ACK, looks good.  We probably opened a can of worms with going SCL puppet and will need to track down other issues going forward with this new path we are using.

I'm sure this isn't the last.

**Comment by bbuckingham** [comment]
@domcleal, Thanks for the feedback.  As @mccun934 mentioned, we'll need to look at the longer term solution to this and he's created issue #2334 to look in to this further.

**Comment by bbuckingham** [comment]
Going to merge, since we need this for proper install.

**Pull request merged**
